#!/bin/sh

APP=
if ! [ -f /boot/home/config/bin/7z ] ; then
	if ! [ -f /boot/home/config/bin/7za ] ; then
		echo "7zip not found" >&2
		exit -1
	else
		APP=7za
	fi
else
	APP=7z
fi

#echo "${APP} $@" >> /boot/home/ark_7zip.log

# Added the below if-check to make sure 7zip is not started
# when there aren't any arguments
if [ "$2" != "" ] ; then
	${APP} "$@" 2>&1
fi
